### ISSUE TITLE
Using Dialogs Defined as Fragments errors in fiori element controller extension

### ISSUE THREAD

**Issue by horsemanjackyliu** [SAP-docs/sapui5#135]
### Issue description

https://sapui5.hana.ondemand.com/#/topic/aeb86c181b9742a2bf88049abf9ccb95
When loadFragment , the result is undefined .
![image](https://github.com/SAP-docs/sapui5/assets/74337345/f74e4952-7b19-4d37-9032-4fd6f0c08ead)
But in network , the result is 200.
![image](https://github.com/SAP-docs/sapui5/assets/74337345/38897440-e6bc-47eb-9a03-d15d11525fcc)
![image](https://github.com/SAP-docs/sapui5/assets/74337345/0b45c021-44d8-4ba1-b5ac-09efaef18c00)

The sap ui5 version is 1.124.1 .

But when the sap ui5 is 1.120.8, the function works in BAS, but after deployed into BTP ABAP environment, it fails again .

### Feedback Type (Optional)

None

**Comment by OlMue** [comment]
Hi @horsemanjackyliu thanks for your feedback. We'll take a look and get back to you.
@KlattG , could you please check (possibly with the devs) if this a documentation issue at all?

**Comment by horsemanjackyliu** [comment]
Hi, Mueller,

i think one possible reason is @sap/ux-specification latest version is 1.120.12 . So if the UI5 version is higher than this, some issue will happens.
https://www.npmjs.com/package/@sap/ux-specification

**Comment by devtomtom** [comment]
Hi @horsemanjackyliu,
Thank you for your feedback.
We need to look into this issue in more detail as it is rather technical. Please report an incident at [https://me.sap.com](https://me.sap.com/createIssue/0).
Best regards!

**Comment by boghyon** [comment]
@horsemanjackyliu

> https://sapui5.hana.ondemand.com/#/topic/aeb86c181b9742a2bf88049abf9ccb95
When loadFragment , the result is undefined .

* The `loadFragment` API referred in the above linked documentation is from [`sap.ui.core.mvc.Controller#loadFragment`](https://ui5.sap.com/#/api/sap.ui.core.mvc.Controller%23methods/loadFragment).
* The `loadFragment` API from the screenshot is from Fiori elements: [`sap.fe.core.ExtensionAPI#loadFragment`](https://ui5.sap.com/#/api/sap.fe.core.ExtensionAPI%23methods/loadFragment). This is an entirely different API with the same name.

Just added an answer in your other question in SAP Community: [The result of loadFragment is undefined. - SAP Community](https://community.sap.com/t5/technology-q-a/the-result-of-loadfragment-is-undefined/qaq-p/13732673/comment-id/4833926#M4833926)

The issue with the `undefined` is probably fixed since SAPUI5 1.112 according to the change I4c9d7565ec4eb88a0919a30d27eaed338332e680 in `sap/fe/core/ExtensionAPI.ts`. It could be possible that the issue is re-introduced in later versions.

To see which SAPUI5 version the app is running with, set the focus on the app UI (not the shell header) and press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left Alt / Left ⌥</kbd>+<kbd>P</kbd>.

**Comment by horsemanjackyliu** [comment]
Boghyon,

You are right! The loadFragment API from the screenshot is from Fiori elements sap.fe.core.ExtensionAPI#loadFragment.
I use SAPUI5 version 1.120.8 in BAS, the issue is overcomed . But after I deploy the Fiori application into BTP ABAP environment. The issue happens again .



Best regards!
Jacky Liu

**Comment by horsemanjackyliu** [comment]
Boghyon,
But I think the issue exists in SAP UI5 version which is after  1.121 .

Best regards!

Jacky Liu

**Comment by horsemanjackyliu** [comment]
Boghyon,
Is it possible to forward the issue to Fiori elements sap.fe.core.ExtensionAPI#loadFragment PM team .Or provide a contact to me .
Best regards!

Jacky Liu
