### ISSUE TITLE
HTML in <code> tags not escaped properly

### ISSUE THREAD

**Issue by mbtools** [SAP-docs/sapui5#17]
The following page contains `&nbsp;` in the sentence `Trailing spaces in text lines are escaped with  in the respective BSP pages.`. 

https://github.com/SAP-docs/sapui5/blob/main/docs/05_Developing_Apps/technical-remarks-5a814d9.md

The markdown is correct. However, it's not rendered right:

https://sapui5.hana.ondemand.com/#/topic/5a814d9945d148b0a1ad941791c3c723

The following is not correct:

```html
<code>&nbsp;</code>
```

The content of the `<code>` tags must be escaped at render. It should be:

```html
<code>&amp;nbsp;</code>
```

Please fix the markdown renderer.

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by OlMue** [comment]
Hi @mbtools 
Thanks for spotting this! For some background: The source both for [https://sapui5.hana.ondemand.com/#/topic/5a814d9945d148b0a1ad941791c3c723](https://sapui5.hana.ondemand.com/#/topic/5a814d9945d148b0a1ad941791c3c723) and for [technical-remarks-5a814d9.md](https://github.com/SAP-docs/sapui5/blob/main/docs/05_Developing_Apps/technical-remarks-5a814d9.md) is a DITA XML file from our content management system. There's no MD renderer involved here.

But something is obviously going wrong between the DITA XML file and the HTML at [https://sapui5.hana.ondemand.com/#/topic/5a814d9945d148b0a1ad941791c3c723](https://sapui5.hana.ondemand.com/#/topic/5a814d9945d148b0a1ad941791c3c723). We're going to check that.

Since this is unrelated to this repo, I'm going to close this.

Thanks!

**Comment by OlMue** [comment]
Thanks again @mbtools! This will be fixed as of 1.110.

**Comment by mbtools** [comment]
https://people.sap.com/marcbernardtools
