### ISSUE TITLE
Transition to TS samples

### ISSUE THREAD

**Issue by dfenerski** [SAP-docs/sapui5#69]
### Issue description

The official endorsement of TypeScript & the drop of the beta for the support for it are great things for the framework and seem to set a positive direction for the future of the technology.

However during a recent visit to the documentation page (and also to the SDK in general) it came to me that all the samples in both the docs & in the mini apps in the 'samples' section still very much use `var _aMyCustomEnum = ['Foo', 'Bar']` type of code.

While providing a general idea, this style of code is not only old but also contradicts the best practices encouraged for both TS & modern ES development, which may mislead or confuse newcomers - videos, books, blogposts all encourage modern ES use while official docs/samples have not been migrated (rewritten).

Therefore I thought it might be good idea to at least ask what the status & plans on possible migration of such samples are?

Are PR's with sample rewrites to be accepted? If yes this could help a bit the core maintainers with the migration effort.

Sorry if this has been clarified somewhere & I am missing it, otherwise It'd be nice to know.

Thanks & BR

Dimitar

  

### Feedback Type (Optional)

clarity

**Comment by KvM2** [comment]
Hi @dfenerski , thanks for your contribution and thorough look at the documentation. We appreciate it and will look into this.

**Comment by OlMue** [comment]
Hi Dimitar, sorry for the long silence and thanks again for bringing this up. We're currently updating the documentation (including the tutorials) to bring it up to modern ES standards and also put more and more emphasis on TypeScript. Revamping the samples is also under discussion, but I can't give you an estimate as to when this will be done.

About your question concerning community contributions: I passed this on to the development colleagues, but there hasn't been a decision yet as to this. If you want to address this again directly to them, I suggest that you open another issue with your suggestion here as well: [https://github.com/SAP/openui5/issues](https://github.com/SAP/openui5/issues).

Since the documentation aspect of your question is addressed now, I will close this issue for now. Thanks again! :-)
