### ISSUE TITLE
Double `#` in the URL on a link on `https://sdk.openui5.org/nightly`

### ISSUE THREAD

**Issue by pubmikeb** [SAP-docs/sapui5#77]
### Issue description

If we check the description of [`sap.ui.core.Core.byId`](https://openui5nightly.hana.ondemand.com/api/sap.ui.core.Core#methods/byId), we find out that this method is deprecated:

> _Deprecated as of version 1.119. Please use [Element.getElementById](https://openui5nightly.hana.ondemand.com/api/sap.ui.core.Element#methods/sap.ui.core.Element.getElementById) instead._

We click on a proposed link and everything is OK.

However, in case of 
https://sdk.openui5.org/nightly/#/api/sap.ui.core.Core%23methods/byId, the proposed link contains an extra `#`: https://sdk.openui5.org/nightly/#/#api/sap.ui.core.Element%23methods/sap.ui.core.Element.getElementById, and this link is wrong, leading to the error:
> The requested resource was not found.

The correct link is:

https://sdk.openui5.org/nightly/#/api/sap.ui.core.Element%23methods/sap.ui.core.Element.getElementById

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

class sap.ui.core.Core.byId

### Page URL on SAP Help Portal (prefilled)

https://sdk.openui5.org/nightly/#/api/sap.ui.core.Core%23methods/byId

**Comment by KvM2** [comment]
Hi @pubmikeb  , thanks for your contribution. We appreciate it and will look into this. This is actually not about the developer guide, but about API docu, but I will pass it on.

**Comment by KvM2** [comment]
Hi @pubmikeb,  you can use the Demo Kit feedback channel for these. If you don't know this feature: You can find it in the Demo Kit under _More information_ (cogwheel) and then select _Give Feedback_ . It also gives you the option to do this in a context-sensitive way for a particular page.

**Comment by KvM2** [comment]
Seems you are in the internal Demo Kit. 🙂 I was referring to the external Demo Kit.

**Comment by boghyon** [comment]
@pubmikeb

The issue seems to be fixed. Could you check again?

___

Regarding other comments..:

> Initially, I've reported this issue on https://github.com/SAP/openui5-docs/issues/89, but that project looks like abandoned

I just published a new PR at https://github.com/SAP/openui5-docs/pull/90. Since OpenUI5 is the core of SAPUI5, I prefer contributing to the `openui5-docs` repo. Only if the change covers SAPUI5 exclusive content, then here in this SAPUI5 docs repo. In the end, it doesn't really matter. The maintainers are very active in both repos! :)

> [...] where should I file API docu-related issues?

API reference is generated from JSDocs as part of the UI5 source code. If the API is from OpenUI5, file the issue at https://github.com/SAP/openui5 

> I assumed that a Give Feedback functionality has been just entirely removed.

I think so too. Also in the stable 1.119 release, the classic "Give Feedback" dialog is gone. :(

**Comment by OlMue** [comment]
> I've just checked the content of https://sdk.openui5.org/nightly/#/api/sap.ui.core.Core%23methods/byId and it looks like the link `Element.getElementById` still contains double `#`:
> 
> > `https://sdk.openui5.org/nightly/#/#api/sap.ui.core.Element%23methods/sap.ui.core.Element.getElementById`
> 
> Perhaps, the fix has not been yet applied to the source code.

Hi @pubmikeb, this is a bit strange. Everything looks and behaves fine in the official version of 1.119 that has been released by now, i.e. [https://sdk.openui5.org/api/sap.ui.core.Core#methods/byId](https://sdk.openui5.org/api/sap.ui.core.Core#methods/byId). So that's fine.

However, in the nightly version which already reflects the dev state of 1.120, the behavior is incorrect. The strange thing is that the URL looks alright in the status bar when I hover over the link:

![image](https://github.com/SAP-docs/sapui5/assets/39769800/13fb2a3b-fb3c-482d-b751-4ed6242ade2e)

When I (left-)click on it, it's also fine at first and opens the correct page. However, opening it with a right-click still leads to the URL with the double `#`. And when I go back to the initial page for the `byId` method, it's also wrong in the status bar.

Weird. I'll address this with the Demo Kit team. I will also close this issue since it's apparently fixed in the official (non-nightly) version.
