### ISSUE TITLE
[doc issue] Generated links don't work multiple times due to missing resource

### ISSUE THREAD

**Issue by RohanAntony** [SAP-docs/sapui5#96]
### Issue description

If you currently go to page [Developing Reuse Components](https://sapui5.hana.ondemand.com/sdk/#/topic/6314fcd2510648fbaad3cee8a421030d.html) and click on the link [Including reuse components on an object page](https://sapui5.hana.ondemand.com/sdk/topic/d869d7ab3caa48b2a20dc20dfa248380.html), the new page throws a "Resource not found" error. 
Although on the github documentation, the link seems to work. 

### Feedback Type (Optional)

linking

**Comment by JannaLisa** [comment]
Hi @RohanAntony ,
Thanks for making us aware that the link doesn't open.
I checked the topic and honestly could find no indication that the link is broken.
I checked 2 other repositories and in both the link opened just fine.
For now, I've simply reset the link.
But I'm afraid we will need to wait until the upcoming version is published again, because I have no other way of testing if the link works or not.
So please be patient, the next version should be available toward the end of December.
In the meantime (I'm sure you've noticed this yourself) I can ask you to simply open the topic by selecting it from the structure on the left. It's 2 topics higher up than the one you selected.
Thanks for now!
